server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: Quick API
  datasource:
    url: jdbc:postgresql://localhost:5432/quick-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect